### PR TITLE
add possibility to configure max frame size

### PR DESCRIPTION
**Pull request by sl0w0rm**
Hi,

we need a way to increase a max frame size in netty. A simple proposal is here. Please merge this or add any other way to configure this parameter.

### CODE REVIEW

**Comment by jurmous** [comment]
I will accept this pull request as is. Maybe the method for configuration will change in the future when more configuration options are added but for now this is ok. (I will add a deprecation warning if it is ever changed)

**Comment by jurmous** [comment]
Am curious: what is the frame size you need for your app? Maybe the default also needs to be different?

**Comment by sl0w0rm** [comment]
We've got:

io.netty.handler.codec.TooLongFrameException: Response entity too large: HttpObjectAggregator$AggregatedFullHttpResponse

when response from etcd (content length) is larger than this value. And 100kB is not much.

**Comment by jurmous** [comment]
And what value do you need? Would 1MB be sufficient?

**Comment by sl0w0rm** [comment]
1MB should be sufficient in most cases but we have a special one and it this stage we don't have paging and a lot of configuration so 4MB are required. If you could release this as 2.3.2 version it would be great.

**Comment by jurmous** [comment]
I have released 2.3.2. I have decided to not yet change the default value. Lets see what other people need.

**Comment by sl0w0rm** [comment]
Great, thanks!

**Pull request merged**
