### PR TITLE
Etcd v2.1: Support basic authentication 

### PR DESCRIPTION
**Pull request by lburgazzoli**
I've added basic support for authentication introduced in Etcd v2.1, 

This PR is not supposed to be merged right now as there is something to be validated/discussed:
- do you want to support Etcd authentication ? :-)
- username/password can be set through EtcdNettyConfig for the moment but authentication is a property of Etcd so I think it would be better to move them in EtcdClient itself
- I've added a new EtcdAuthenticationException but maybe we can adapt EtcdException to cover more cases

### CODE REVIEW

**Comment by jurmous** [comment]
Wow great work!

Yes I want to support the new etcd authentication in etcd4j. Was looking into it earlier today but decided to not yet work on it. Thanks for doing the work!

Have not yet decided how to support the authentication. It sounds in theory good in EtcdClient. 
Yes the Exception is different. Don't know yet what is best. 

Will look into your pull request later and think about your questions. (Probably tomorrow) Thanks for the great work! Let's get this into etcd4j.

**Comment by lburgazzoli** [comment]
Btw, EtcdAuthenticationException is not complete as today as it gets the JSON body as is, if you think this exception makes sense, I will complete it so it properly takes the message from the JSON body.

**Comment by lburgazzoli** [comment]
I've noticed that as today the EtcdException is instantiated looking at the body of the response, shouldn't be better to use the HTTP status code? 

Something like 

Code | Exception
------- | ----
404 | EtcdKeyException
401 | EtcdAuthorizationException
* | EtcdException

**Comment by jurmous** [comment]
I am ok with this implementation! Are there still open question marks or problems with it? EtcdClient config options looks good.

If I am correct there can be EtcdKeyExceptions with more Response codes, not only with 404 not found. So it still seems the best to fall back

**Comment by lburgazzoli** [comment]
About authentication, no open point so far.

About exception, yes it still need some more investigation but we can add know handler for http status code and fallback on a "smart" error decoder, I can work on it if you agree.

**Comment by lburgazzoli** [comment]
Hello, nay plan to merge it ?

**Comment by jurmous** [comment]
Hello Luca, it seems I am too busy with my new work to have the mindspace I need to work on this project. I currently do not work with etcd and any off time is for now away from the computer. With all the good work you already are doing I am giving you rights to collaborate to this project so you can merge yourself. When you think a new release can be done just give me a sign and I will run the maven publish task. If you need my help just mention me or send an email to jurmous[ at ]jurmo[ dot ]us

**Comment by lburgazzoli** [comment]
Thank you to share your work with me.

I'm going to create a new branch to incorporate all the PR I've opened then I will ask you for a quick review as it is your project and I do not want it to move in a direction you do not want.

**Pull request merged**
