### PR TITLE
Json handling Improvements

### PR DESCRIPTION
**Pull request by lburgazzoli**
This PR is aimed to improve some part of the JSON handling:
* use of Jackson's ObjectMapper and annotations instead of manual JSON unwrapping
* make responses immutable (private fields, set field in contsructor only, etc. ) 

This is a quite intrusive PR so let me know what you think about.

### CODE REVIEW

**Comment by jurmous** [comment]
Thanks for the suggestion. I have some remarks and questions.

- I see you use 4 spaces in your formatting. I use 2 spaces. This causes a lot more diffs than needed.
- I agree with that the objects should be immutable. I would like to change that.
- Why do you prefer the ObjectMapper? With the simplicity of the JSON I wanted to use the basic Jackson classes which is also used by ObjectMapper internally so it would be faster and uses less dependencies. Looking at the resulting change it is not like that the new code is much shorter although some parsing code is removed. Just curious what is your thinking :) (I can be tempted both ways at the moment)
- I can't change the resulting objects like node to methods. That would make the code incompatible with all existing applications which use etcd4j. So the properties need to be exposed but they can become final.

**Comment by lburgazzoli** [comment]
- my mistake, most likely my ide decided to adapt your code to my style which should not have happened
- good
- I prefer ObjectMapper because it makes the model self describing and I only have to change the code in on one place (btw, the etcd json is quite simple so a new field would not require so much work but I'm lazy)
- that is not a problem at all al make properties final would be good enough however you maybe break the APIs ( of course if you like). In my own implementation of an etcd client (before I noticed your repo) I added some helper methods to the 'node' class like hasChildren(), expiresIn() and so on so access attributes via methods was the right choice for consistency

**Comment by jurmous** [comment]
I merged your code in a separate pull request in another branch and reworked it before merging with master. It has just been released into 2.7.0 with some other fixes.

For now I do not yet adapt the ObjectMapper to keep dependencies lighter and code a bit faster. (No annotation processing etc needed at startup) But it is good to have your code in the repo for when I reconsider.

The returned objects now have final properties. It is indeed a change in API but I don't expect people to rewrite them after return so I think for most it is not a problem.

Thanks again for your contribution! 

Oh I now see I missed your suggestion for the helper methods, will consider them for a next release :) Do you have more suggestions besides the ones you mentioned?

**Comment by lburgazzoli** [comment]
I can tell you what I had in my own code and what was in the pipe:

* value converter: I had a method in EtcdNode like <T> T value(Class<T> type) to convert the value field to a type and because in my project every value in etcd have to be of type json, ObjectMapper was really useful. I had a plan to add  generic ValueConverter interface an the possibility to register it via a fluent ClientBuilder
* directory walking a filtering: I had a plan to add file system like walking to EtcdNode, same pattern can be used to apply a filter to a recursive get and returns only a subtree
* tree to properties: as etcd is often used to store configuration properties I had a toPeoperties() method in EtcdNode

**Comment by jurmous** [comment]
Yes they sound like useful methods but am not sure to add them to the core jar. Maybe we could add them to a new folder/sourceset/jar building on top of etcd4j. Since they move the api away from core etcd communications and towards a config system.

Maybe a layer could be made on top of etcd4j to help people do configs more easily. Just like the ObjectMapper jar is built upon Jackson its core jar to make working with json more confenient.

I am currently going on my holidays so we have to see afterwards what we do. :smile: If you have code ready you are always welcome to do a PR. Please keep them small so we can see on a case of case basis.

**Comment by lburgazzoli** [comment]
I think value converter can be include on core and other methods can be added to an helper class, sourceset, jar

Maybe you can restructure your repo like:
- etcd4j-core
- etcd4j-xyz

**Pull request merged**
