### PR TITLE
fixing chunked encoding problem

### PR DESCRIPTION
**Pull request by zlooo**
Fix for https://github.com/jurmous/etcd4j/issues/37

### CODE REVIEW

**Comment by jurmous** [comment]
Thanks for the fix!

Is it possible that you use the code style of this project or turn off the auto format on save so the old lines stay the same? This way it is easier for me to see the changes and merge them. 

Intellij idea code style:
http://cl.ly/213l3K103k0U

To check if I saw correctly what you did: You added a ChunkedWriter to the pipeline and rewrote createHttpRequest a bit to combine methods?

**Comment by jurmous** [comment]
I merged this commit in another pull request and it was released in 2.4.0

**Comment by zlooo** [comment]
Sorry for different formatting, I know it can be a real pain to see real differences in reformatted classes. It's a habit of mine to always format code and since I used Eclipse not Intellij different styles must have been applied.

Regarding changes, yes one is adding ChunkedWriter and the other important one is
    if (bodyRequestEncoder != null && bodyRequestEncoder.isChunked()) {
      future = channel.write(bodyRequestEncoder);
    }
That's why I merged those 2 functions together.

**Comment by jurmous** [comment]
Ah well, don't worry. I managed with the formatting issues. But maybe it is easy to turn off auto format for this project before changing the code? :blush: 
Ah yes. Thanks for all the contributions! :smiley:

**Pull request closed without merging**
