### PR TITLE
Added gettter to support using etcd4j client as dependency in unit test

### PR DESCRIPTION
**Pull request by timgesekus**
We do a lot of unit testing and having etcd4j as a dependency renders unit testing nearly impossible. Because of private contructors and using plain fields, that can't be mocked. With added getters, it is as least possible together with powermock to mock an etcd4j client.

### CODE REVIEW

**Comment by lburgazzoli** [comment]
Could you add getters to EtcdVersionResponse too ?

**Comment by timgesekus** [comment]
Done

**Comment by lburgazzoli** [comment]
thank you

**Comment by lburgazzoli** [comment]
thank you

**Comment by timgesekus** [comment]
Welcome. I love the API. Started a client myself before stumbling over this. Saved me a lot of work.

**Pull request merged**
