### PR TITLE
Easy-to-configure TLS and Mutual TLS client connections

### PR DESCRIPTION
**Pull request by dgutierrez-stratio**
Provides support for TLS connections to etcd (non mutual and mutual TLS) by using Java's Truststore and Keystore mechanisms. Etcd clients can now be configured as follows

```java
EtcdClient etcd = new EtcdClient(SecurityContextBuilder.forKeystoreAndTruststore(
                "/keystore.jks",
                "keystore_pass",
                "/truststore.jks",
                "truststore_pass"
        ), new URI("https://127.0.0.1:2379"));
```

### CODE REVIEW

**Comment by lburgazzoli** [comment]
would it be possible to include a proper ssl test ?

**Comment by dgutierrez-stratio** [comment]
Yes, that's probably a good idea. But I'd work first on mocking etcd for every test.. I'll see what I can do!

**Comment by dgutierrez-stratio** [comment]
Hi, I've refactored the test suite, but it requires an external etcd with security enabled. In order for these tests to work we need

1. External Etcd server with security enabled
2. Truststore and keystore for the test suite, trusted by the Etcd server

How do you propose to resolve this issue?

**Comment by lburgazzoli** [comment]
the task `dockerTest` executes the test against an etcd instance running in docker so an additional instance with ssl configured can be started, you should include a script/gradle-task to generate the jks. the keystore can be included in src/test/resources or generated on demand if there is a dedicated gradle task

**Comment by dgutierrez-stratio** [comment]
Done! Check it out please. I've tested it and everyting runs fine in our servers

**Comment by lburgazzoli** [comment]
Just some minor notes:
- would it be possible to include a script to generate the certs ?
- can you squash your commits in a single one ?

**Comment by dgutierrez-stratio** [comment]
I can provide an example script under resources/certs of how I generated those certificates, but I can't spend any more time making a gradle task generate them on demand, sorry

**Comment by lburgazzoli** [comment]
That would be more than enough,thx

**Comment by dgutierrez-stratio** [comment]
Squashed! Thank you for your help!

**Pull request merged**
