### PR TITLE
Upgrade Netty to version 4.1.11.Final

### PR DESCRIPTION
**Pull request by oscerd**

### CODE REVIEW

**Comment by lburgazzoli** [comment]
Thx

**Comment by bobpaulin** [comment]
Is there any chance we can get a release cut on master in the near future?  I'm trying to use etcd4j 2.13.0 with apache camel 2.20.1 and the netty versions are incompatable due to a breaking change in io.netty.resolver.dns.DnsAddressResolverGroup
exception is
Caused by: java.lang.NoSuchMethodError: io.netty.resolver.dns.DnsAddressResolverGroup.<init>(Ljava/lang/Class;Lio/netty/resolver/dns/DnsServerAddresses;)V

This issue appears to be fixed in the master branch with the upgrade in this PR.

**Comment by oscerd** [comment]
@lburgazzoli can we release a new version?

**Comment by lburgazzoli** [comment]
2.14.0 released

**Pull request merged**
