### PR TITLE
Adding builders which give more configuration options to the user

### PR DESCRIPTION
**Pull request by zlooo**
I wanted to have more control over internals of EtcdNettyClient. Feel free to use builders I've written if you like the idea

### CODE REVIEW

**Comment by jurmous** [comment]
Thanks for contributing the work back! I need some extra time to chew on the idea.

Which options where needed for your specific needs so you created the builder structure. Was it primarily passing in an Eventloop from a higher level and setting the connect timeout? Or did you have more needs?

**Comment by zlooo** [comment]
My primary need was passing in event loop. I already use netty in my app and I do not want to create new threads needlessly. Remember that by default each NioEventLoopGroup creates 2 * (available cores) threads. Of course you can change that with io.netty.eventLoopThreads option but it's a global setting. That's why I want to reuse event loop I've already created in my app.

**Comment by jurmous** [comment]
The EventLoopGroup is a valid concern.

I pulled your changes into a new branch here to look at it. I am closing this pull request since it is now redundant. I couldn't use it since it is targeted at master.

**Comment by jurmous** [comment]
I have chosen to not use builders but to add a config class option to EtcdNettyClient constructor. This way it is simpler and more versatile than the builder. I added some more configuration options to it. You are still able to add your own builders to create an EtcdClient in your own code. I included an example on the bottom of the README page. Thanks for the suggestions!

**Pull request closed without merging**
